name: Run Tests on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on PR open, update, or re-open
    branches:
      - 'main'  # Run tests on PR targeting the main branch

jobs:
  test:
    name: "Run tests with Docker"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Compose services
        run: |
          docker-compose up -d postgres
          # Wait for PostgreSQL to be ready
          echo "Waiting for PostgreSQL to be ready..."
          timeout 30s bash -c 'until docker exec my_postgres pg_isready -U myuser -d mydatabase; do sleep 1; done'

      - name: Run Go tests
        run: |
          go test ./... -v  # Run tests in all directories
        env:
          # Make database connection details available to tests
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: myuser
          DB_PASSWORD: mypassword
          DB_NAME: mydatabase

      - name: Stop Docker Compose services
        if: always()  # Always run this step, even if previous steps fail
        run: docker-compose down