name: Run Tests and Commit Changes on PR Opened and Merged

on:
  pull_request:
    types: [opened]  # Trigger when PR is opened
    branches:
      - 'main'

jobs:
  test_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Run Go tests
        run: |
          go test ./... -v  # Run tests in all directories

      - name: Commit and Push changes if tests pass and PR was merged
        if: success() && github.event.pull_request.merged == true  # Only commit if tests passed and PR was merged
        run: |
          # Check if there are any changes (to avoid committing when there are none)
          git diff --exit-code || (
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"

            # Add changes to git
            git add .

            # Commit changes with a default message
            git commit -m "Automated commit after successful test run"

            # Push changes to the current branch (main)
            git push origin HEAD
          )
